# Generated by Django 5.0.6 on 2026-07-02 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoundItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('electronics', 'Electronics'), ('id_cards', 'ID Cards'), ('books', 'Books'), ('wallets', 'Wallets'), ('keys', 'Keys'), ('accessories', 'Accessories'), ('clothing', 'Clothing'), ('others', 'Others')], max_length=20)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='found_items/')),
                ('location', models.CharField(help_text='Found location', max_length=150)),
                ('date_found', models.DateField()),
                ('contact_info', models.CharField(help_text='Phone or email to contact', max_length=150)),
                ('status', models.CharField(choices=[('active', 'Active'), ('returned', 'Returned')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='found_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LostItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('electronics', 'Electronics'), ('id_cards', 'ID Cards'), ('books', 'Books'), ('wallets', 'Wallets'), ('keys', 'Keys'), ('accessories', 'Accessories'), ('clothing', 'Clothing'), ('others', 'Others')], max_length=20)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='lost_items/')),
                ('location', models.CharField(help_text='Last seen location', max_length=150)),
                ('date_lost', models.DateField()),
                ('reward', models.CharField(blank=True, help_text='Optional reward', max_length=100)),
                ('contact_info', models.CharField(help_text='Phone or email to contact', max_length=150)),
                ('status', models.CharField(choices=[('active', 'Active'), ('found', 'Found')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lost_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('notif_type', models.CharField(choices=[('match', 'Potential Match'), ('returned', 'Item Returned'), ('announcement', 'Admin Announcement')], default='announcement', max_length=15)),
                ('link', models.CharField(blank=True, max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
